[package]
name = "FieldAssist"
version = "0.6.3"
edition = "2021"
description = "Review, edit, and process audio coming in from the field"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
schemars = "1.0"
gpui-kit = "0.6.1"
symphonia = { version = "0.6", features = ["all"] }
cpal = "0.18"
mlua = { version = "0.12", features = ["lua54", "vendored"] }
hound = "3"
rusty_vorbis = "0.1"
ogg = "0.9"
flacenc = "0.5"
rubato = { version = "5", features = ["fft_resampler"] }


[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Console"] }

[build-dependencies]
embed-resource = "3"

[profile.dev.package]
gpui-pre = { opt-level = 3 }
gpui-pre-platform = { opt-level = 3 }
